INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'África');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(1, 'Cristián', 'Pérez', 'crisperez@admin.com', '2023-11-05');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, 'Alejandra', 'Fuentes', 'alefuentes@gmail.com', '2023-11-06');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Mauricio', 'Pérez', 'mauro@gmail.com', '2023-11-06');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(5, 'Claudia', 'Pérez', 'claudia@gmail.com', '2023-11-07');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(8, 'Sara', 'Vásquez', 'saravasquez@gmail.com', '2023-11-08');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, 'Rodrigo', 'Pérez', 'rodrigo@gmail.com', '2023-11-09');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(6, 'Héctor', 'Pérez', 'hector@gmail.com', '2023-11-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(6, 'Javier', 'Pérez', 'javier@gmail.com', '2023-11-11');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(7, 'Alejandro', 'Soto', 'alejandro@gmail.com', '2023-11-12');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(1, 'Verónica', 'G', 'veronica@gmail.com', '2023-11-13');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, 'Eddard', 'Stark', 'eddard@gmail.com', '2023-11-14');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Catelyn', 'Tully', 'catelyn@gmail.com', '2023-11-15');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Robb', 'Stark', 'robb@gmail.com', '2023-11-16');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Daenerys', 'Targaryen', 'daenerys@gmail.com', '2023-11-17');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, 'Ramsay', 'Snow', 'ramsay@gmail.com', '2023-11-18');